### ISSUE TITLE
Update to newer version of Storage

### ISSUE THREAD

**Issue by NiklasArbin** [Azure/azure-sdk-for-media-services-extensions#38]
Method not found: 'System.Threading.Tasks.Task`1<System.String> Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.StartCopyFromBlobAsync(Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob, Microsoft.WindowsAzure.Storage.AccessCondition, Microsoft.WindowsAzure.Storage.AccessCondition, Microsoft.WindowsAzure.Storage.Blob.BlobRequestOptions, Microsoft.WindowsAzure.Storage.OperationContext, System.Threading.CancellationToken)'.

When using storage sdk 7.2.1

**Comment by norrisj9** [comment]
Getting the same issue with storage 8.1.1

Message=Method not found: 'System.Threading.Tasks.Task`1<System.String> Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.StartCopyFromBlobAsync(Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob, Microsoft.WindowsAzure.Storage.AccessCondition, Microsoft.WindowsAzure.Storage.AccessCondition, Microsoft.WindowsAzure.Storage.Blob.BlobRequestOptions, Microsoft.WindowsAzure.Storage.OperationContext, System.Threading.CancellationToken)'.

**Comment by NiklasArbin** [comment]
I fixed it by including my own version of the class CopyBlobHelpers with updated signature to match the new storage API https://github.com/Azure/azure-sdk-for-media-services-extensions/blob/dev/MediaServices.Client.Extensions/CopyBlobHelpers.cs/

**Comment by nitro52** [comment]
Had this same issue with azure functions, this explains my issue

http://stackoverflow.com/questions/43860054/azure-functions-method-not-found-error/43875559#43875559

downgrading to 7.2.1 worked with the code sample i was use.

**Comment by mclausen** [comment]
Hi Dev team,

Is this task going to be revisited any time soon?

**Comment by mmartain** [comment]
Cannot get around this problem either.

**Comment by nitro52** [comment]
I ran into this problem again and thought i would take a look at it myself. I've just submitted a pull request that should fix the issue.

**Comment by Lukasz994** [comment]
It has been over two years and issue is still present. Is there a chance for a permanent fix?
